-- qualified_teams for r32 — 3-letter codes, matches squads-complete.json and fixtures-r32.json
insert into public.qualified_teams (round, team_code) values
  ('r32', 'ALG'),
  ('r32', 'ARG'),
  ('r32', 'AUS'),
  ('r32', 'AUT'),
  ('r32', 'BEL'),
  ('r32', 'BIH'),
  ('r32', 'BRA'),
  ('r32', 'CAN'),
  ('r32', 'CIV'),
  ('r32', 'COD'),
  ('r32', 'COL'),
  ('r32', 'CPV'),
  ('r32', 'CRO'),
  ('r32', 'ECU'),
  ('r32', 'EGY'),
  ('r32', 'ENG'),
  ('r32', 'ESP'),
  ('r32', 'FRA'),
  ('r32', 'GER'),
  ('r32', 'GHA'),
  ('r32', 'JPN'),
  ('r32', 'MAR'),
  ('r32', 'MEX'),
  ('r32', 'NED'),
  ('r32', 'NOR'),
  ('r32', 'PAR'),
  ('r32', 'POR'),
  ('r32', 'RSA'),
  ('r32', 'SEN'),
  ('r32', 'SUI'),
  ('r32', 'SWE'),
  ('r32', 'USA')
on conflict do nothing;
