-- ============================================================
-- scenario_r16.sql — Sedicesimi completati, Ottavi live
-- Usa i risultati reali da round-results.json
-- ============================================================

update public.round_state set state = 'completed', updated_at = now() where round = 'r32';
update public.round_state set state = 'live',      updated_at = now() where round = 'r16';

-- ── Risultati Sedicesimi ─────────────────────────────────────
insert into public.match_data
  (round, match_id, home_team, away_team, home_score, away_score, completed, winner_team, player_stats)
values
  ('r32','r32_01','Brazil','Egypt',2,0,true,'Brazil',
   '{"Vinicius Jr.|Brazil":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Rodrygo|Brazil":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Bruno Guimarães|Brazil":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Lucas Paquetá|Brazil":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Casemiro|Brazil":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Salah|Egypt":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false}}'::jsonb),
  ('r32','r32_02','Argentina','Costa Rica',3,1,true,'Argentina',
   '{"Messi|Argentina":{"played":true,"goals":2,"assists":1,"yellow":false,"red":false,"penScored":true,"penMissed":false,"ownGoal":false},
     "Lautaro Martínez|Argentina":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Di María|Argentina":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Paredes|Argentina":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Campbell|Costa Rica":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Bryan Ruiz|Costa Rica":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Waston|Costa Rica":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false}}'::jsonb),
  ('r32','r32_03','France','Nigeria',2,1,true,'France',
   '{"Mbappé|France":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Giroud|France":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Dembélé|France":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Griezmann|France":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Koundé|France":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Osimhen|Nigeria":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Lookman|Nigeria":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Collins|Nigeria":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false}}'::jsonb),
  ('r32','r32_04','England','Senegal',2,0,true,'England',
   '{"Bellingham|England":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Kane|England":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Foden|England":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Saka|England":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Trippier|England":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Guèye|Senegal":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false}}'::jsonb),
  ('r32','r32_05','Spain','Serbia',3,0,true,'Spain',
   '{"Pedri|Spain":{"played":true,"goals":1,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Yamal|Spain":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Olmo|Spain":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Gavi|Spain":{"played":true,"goals":0,"assists":1,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Morata|Spain":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Milinković-Savić|Serbia":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Mitrović|Serbia":{"played":true,"goals":0,"assists":0,"yellow":false,"red":true,"penScored":false,"penMissed":false,"ownGoal":false}}'::jsonb),
  ('r32','r32_06','Germany','Chile',3,1,true,'Germany',
   '{"Wirtz|Germany":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Havertz|Germany":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Füllkrug|Germany":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Musiala|Germany":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Gnabry|Germany":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Kroos|Germany":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Brereton Díaz|Chile":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Alexis Sánchez|Chile":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Medel|Chile":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Vidal|Chile":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false}}'::jsonb),
  ('r32','r32_07','Portugal','Colombia',4,1,true,'Portugal',
   '{"Ronaldo|Portugal":{"played":true,"goals":3,"assists":0,"yellow":false,"red":false,"penScored":true,"penMissed":false,"ownGoal":false},
     "Bruno Fernandes|Portugal":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Cancelo|Portugal":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Rúben Neves|Portugal":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Diogo Jota|Portugal":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Rúben Dias|Portugal":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Luis Díaz|Colombia":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "J. Rodríguez|Colombia":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "D. Sánchez|Colombia":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false}}'::jsonb),
  ('r32','r32_08','Netherlands','Ecuador',1,0,true,'Netherlands',
   '{"Dumfries|Netherlands":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Depay|Netherlands":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "de Vrij|Netherlands":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Caicedo|Ecuador":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false}}'::jsonb),
  ('r32','r32_09','Italy','Switzerland',2,1,true,'Italy',
   '{"Barella|Italy":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Retegui|Italy":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Dimarco|Italy":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Frattesi|Italy":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Acerbi|Italy":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Embolo|Switzerland":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Xhaka|Switzerland":{"played":true,"goals":0,"assists":1,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Shaqiri|Switzerland":{"played":true,"goals":0,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":true,"ownGoal":false}}'::jsonb),
  ('r32','r32_10','Belgium','South Korea',3,2,true,'Belgium',
   '{"De Bruyne|Belgium":{"played":true,"goals":2,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Lukaku|Belgium":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":true,"penMissed":false,"ownGoal":false},
     "Doku|Belgium":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Tielemans|Belgium":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Witsel|Belgium":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Son|South Korea":{"played":true,"goals":2,"assists":0,"yellow":false,"red":false,"penScored":true,"penMissed":false,"ownGoal":false},
     "Hwang Hee-chan|South Korea":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Kim Min-Jae|South Korea":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false}}'::jsonb),
  ('r32','r32_11','Croatia','Morocco',0,1,true,'Morocco',
   '{"Ziyech|Morocco":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Hakimi|Morocco":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Modrić|Croatia":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Brozović|Croatia":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false}}'::jsonb),
  ('r32','r32_12','Uruguay','Austria',2,0,true,'Uruguay',
   '{"Darwin Núñez|Uruguay":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Valverde|Uruguay":{"played":true,"goals":1,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "L. Suárez|Uruguay":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Bentancur|Uruguay":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Laimer|Austria":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false}}'::jsonb),
  ('r32','r32_13','Mexico','Poland',1,2,true,'Poland',
   '{"Lewandowski|Poland":{"played":true,"goals":2,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Zieliński|Poland":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Szymański|Poland":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Krychowiak|Poland":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "H. Lozano|Mexico":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Pineda|Mexico":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Edson Álvarez|Mexico":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false}}'::jsonb),
  ('r32','r32_14','Denmark','Japan',1,1,true,'Japan',
   '{"Eriksen|Denmark":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Braithwaite|Denmark":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Andersen|Denmark":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Mitoma|Japan":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Kubo|Japan":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Wataru Endō|Japan":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false}}'::jsonb),
  ('r32','r32_15','Sweden','USA',0,1,true,'USA',
   '{"Pulisic|USA":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Reyna|USA":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Adams|USA":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Forsberg|Sweden":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false}}'::jsonb),
  ('r32','r32_16','Wales','Canada',1,2,true,'Canada',
   '{"Davies|Canada":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "David|Canada":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Buchanan|Canada":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Eustáquio|Canada":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Vitória|Canada":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Bale|Wales":{"played":true,"goals":1,"assists":0,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Dan James|Wales":{"played":true,"goals":0,"assists":1,"yellow":false,"red":false,"penScored":false,"penMissed":false,"ownGoal":false},
     "Ramsey|Wales":{"played":true,"goals":0,"assists":0,"yellow":true,"red":false,"penScored":false,"penMissed":false,"ownGoal":false}}'::jsonb)
on conflict (round, match_id) do update
  set home_score = excluded.home_score, away_score = excluded.away_score,
      completed = excluded.completed, winner_team = excluded.winner_team,
      player_stats = excluded.player_stats, updated_at = now();

-- ── 16 qualificate agli Ottavi ───────────────────────────────
-- Winners: Brazil, Argentina, France, England, Spain, Germany, Portugal, Netherlands,
--          Italy, Belgium, Morocco, Uruguay, Poland, Japan, USA, Canada
insert into public.qualified_teams (round, team_code) values
  ('r16', 'Brazil'), ('r16', 'Argentina'), ('r16', 'France'), ('r16', 'England'),
  ('r16', 'Spain'),  ('r16', 'Germany'),   ('r16', 'Portugal'),('r16', 'Netherlands'),
  ('r16', 'Italy'),  ('r16', 'Belgium'),   ('r16', 'Morocco'), ('r16', 'Uruguay'),
  ('r16', 'Poland'), ('r16', 'Japan'),     ('r16', 'USA'),     ('r16', 'Canada')
on conflict do nothing;

-- ── Draft di esempio per gli Ottavi ─────────────────────────
insert into public.drafts
  (nickname, round, coach, picks, formation, captain, score, ct_bonus_applied, ts)
values
  ('Tifoso_Milano', 'r16',
   '{"name":"Ancelotti","team":"Spain","flag":"🇪🇸","formation":"4-3-3"}',
   '[
     {"name":"Donnarumma","team":"Italy","role":"P","stars":5,"flag":"🇮🇹","pts":0,"finalPts":0,"isCaptain":false},
     {"name":"Hakimi","team":"Morocco","role":"D","stars":4,"flag":"🇲🇦","pts":0,"finalPts":0,"isCaptain":false},
     {"name":"Rúben Dias","team":"Portugal","role":"D","stars":5,"flag":"🇵🇹","pts":0,"finalPts":0,"isCaptain":false},
     {"name":"Cancelo","team":"Portugal","role":"D","stars":4,"flag":"🇵🇹","pts":0,"finalPts":0,"isCaptain":false},
     {"name":"Davies","team":"Canada","role":"D","stars":4,"flag":"🇨🇦","pts":0,"finalPts":0,"isCaptain":false},
     {"name":"Mbappé","team":"France","role":"A","stars":5,"flag":"🇫🇷","pts":0,"finalPts":0,"isCaptain":true},
     {"name":"Vinicius Jr.","team":"Brazil","role":"A","stars":5,"flag":"🇧🇷","pts":0,"finalPts":0,"isCaptain":false},
     {"name":"Lewandowski","team":"Poland","role":"A","stars":5,"flag":"🇵🇱","pts":0,"finalPts":0,"isCaptain":false},
     {"name":"Pedri","team":"Spain","role":"C","stars":5,"flag":"🇪🇸","pts":0,"finalPts":0,"isCaptain":false},
     {"name":"De Bruyne","team":"Belgium","role":"C","stars":5,"flag":"🇧🇪","pts":0,"finalPts":0,"isCaptain":false},
     {"name":"Bellingham","team":"England","role":"C","stars":5,"flag":"🏴󠁧󠁢󠁥󠁮󠁧󠁿","pts":0,"finalPts":0,"isCaptain":false}
   ]',
   '"4-3-3"', 'Mbappé|France', 0, false,
   extract(epoch from now() - interval '6 minutes') * 1000),
  ('DraftKing99', 'r16',
   '{"name":"Guardiola","team":"Spain","flag":"🇪🇸","formation":"4-3-3"}',
   '[
     {"name":"Neuer","team":"Germany","role":"P","stars":4,"flag":"🇩🇪","pts":0,"finalPts":0,"isCaptain":false},
     {"name":"Koundé","team":"France","role":"D","stars":4,"flag":"🇫🇷","pts":0,"finalPts":0,"isCaptain":false},
     {"name":"Varane","team":"France","role":"D","stars":4,"flag":"🇫🇷","pts":0,"finalPts":0,"isCaptain":false},
     {"name":"de Vrij","team":"Netherlands","role":"D","stars":3,"flag":"🇳🇱","pts":0,"finalPts":0,"isCaptain":false},
     {"name":"Trippier","team":"England","role":"D","stars":3,"flag":"🏴󠁧󠁢󠁥󠁮󠁧󠁿","pts":0,"finalPts":0,"isCaptain":false},
     {"name":"Ronaldo","team":"Portugal","role":"A","stars":4,"flag":"🇵🇹","pts":0,"finalPts":0,"isCaptain":true},
     {"name":"Kane","team":"England","role":"A","stars":5,"flag":"🏴󠁧󠁢󠁥󠁮󠁧󠁿","pts":0,"finalPts":0,"isCaptain":false},
     {"name":"Messi","team":"Argentina","role":"A","stars":5,"flag":"🇦🇷","pts":0,"finalPts":0,"isCaptain":false},
     {"name":"Kroos","team":"Germany","role":"C","stars":5,"flag":"🇩🇪","pts":0,"finalPts":0,"isCaptain":false},
     {"name":"Musiala","team":"Germany","role":"C","stars":5,"flag":"🇩🇪","pts":0,"finalPts":0,"isCaptain":false},
     {"name":"Barella","team":"Italy","role":"C","stars":4,"flag":"🇮🇹","pts":0,"finalPts":0,"isCaptain":false}
   ]',
   '"4-3-3"', 'Ronaldo|Portugal', 0, false,
   extract(epoch from now() - interval '4 minutes') * 1000)
on conflict (round, nickname) do update
  set picks = excluded.picks, coach = excluded.coach, formation = excluded.formation,
      captain = excluded.captain, score = 0, ct_bonus_applied = false,
      ts = excluded.ts, updated_at = now();
